version: "3.7"

services:
#    sim:
#        image: node:12-alpine
#        # command: sh -c "npm install && npm run upload couchdb admin:password"
#        # really shouldn't provide the password here, this is just a proof of concept!
#        command: sh -c "npm install && npm run server"
#        ports:
#            - 43210:43210
#        working_dir: /sim
#        volumes:
#            - ./:/sim

#    vertx:
#        image: dune/vertx
#        ports:
#            - 8080:8080

    couchdb:
        image: couchdb:latest
        ports:
            - 5984:5984 # don't want people logging into fauxton unencrypted...
            - 6984:6984
        volumes:
            - ./couchdb/config:/opt/couchdb/etc/local.d/
            - ./couchdb/data:/opt/couchdb/data
            - ./couchdb/cert:/etc/couchdb/cert
        # environment:
            # COUCHDB_USER: "admin"
            # COUCHDB_PASSWORD: "password"
        # you only need this when first configuring the server

