version: "3.7"

services:
    sim: 
        image: node:12-alpine
        command: sh -c "npm install && npm run start"
        working_dir: /sim
        volumes:
            - ./:/sim

    couchdb:
        image: couchdb:latest
        ports:
            - 5984:5984
        volumes:
            - ./couchdb/config:/opt/couchdb/etc/local.d/
            - ./couchdb/data:/opt/couchdb/data
        environment:
            COUCHDB_USER: "admin"
            COUCHDB_PASSWORD: "secret"